### PR TITLE
feat: make xml and json parser not depend on vrdr ig and vrdr messaging ig structure definitions being present in the bundle

### PR DESCRIPTION
**Pull request by consultantusa**

### CODE REVIEW

**Comment by whichwit** [comment]
Is this ready to be reviewed? Confirming since it's been awhile.

**Comment by consultantusa** [comment]
Is the requirement asking for rewriting HAPI parsers? Almost all current (test) bundles have structure definition in meta profiles and extension urls.

**Comment by MikeRileyGTRI** [comment]
What was the intention behind this issue? HAPI FHIR parsing needs to have appropriate profile definitions within the serialized resources in order for parsing to occur correctly; and it's a requirement of the IG that implementors provide those profile statements in the resources explicitly. Remove that requirement breaks validation.

**Comment by consultantusa** [comment]
This is Mr. Burns' reply when I asked him last month: 'For the first one issue #10, it’s to allow loading the json without a “meta profile” field, but this is lower priority so we can ignore for now.'

**Comment by whichwit** [comment]
This request was submitted earlier this year. A lot had changed, both the IGs and programming. We need to re-evaluate the relevancy of these older entries.

**Pull request closed without merging**
